### ISSUE TITLE
Getting: The application did not respond

### ISSUE THREAD

**Issue by prakashfw** [wotschofsky/discord-live-translator#39]
Getting this issue

<img width="656" alt="Screenshot 2023-08-16 at 02 20 43" src="https://github.com/wotschofsky/discord-live-translator/assets/79567766/298df1eb-2e4e-4bb5-8620-132455b0514c">

**Comment by Medriane** [comment]
Same here.. Tried to give all permissions, but continues not working

**Comment by Medriane** [comment]
the bot is offline

**Comment by wotschofsky** [comment]
Hi @prakashfw, thanks for reporting this. The commands are failing, because the bot is currently offline.

Reason being that I currently don't have the hardware to run the bot 24/7 with good performance.
Example: On my M1 Pro Mac translation takes ~4s while on the server hardware I have access to, it takes ~50s, which is absolutely unacceptable.
I am currently looking for a solution, but my options are mostly limited by the fact that I have absolutely no income from this and can therefore not justify spending hundreds on hosting each month.

Be assured that I am actively looking for a solution to this! If you or a person you know has a solution to this, I am happy to hear from you.

**Comment by wotschofsky** [comment]
In the meantime, I've recently added a Docker Compose file to the repo, with which you can spin up your own bot instance with very little effort required.

**Comment by AegisPatris** [comment]
Charge us for this service we will pay

**Comment by wotschofsky** [comment]
Soon the wait will be over. I think I found a solution :)
https://x.com/wotschofsky/status/1818643753940193662

**Comment by wotschofsky** [comment]
The bot is now finally back up and running! 🎉 
English to something currently works by far the best - I'll improve the other soon

Looking foward to any feedback
