### ISSUE TITLE
No slash commands when self-hosting

### ISSUE THREAD

**Issue by resiez** [wotschofsky/discord-live-translator#40]
I decided to try to self-host the bot with docker, following the instructions. The bot shows as Online and I was able to add it to my server, but there are no slash commands for the bot. Is there something I need to do that isn't listed in the instructions to get slash commands to work?

**Comment by eliteprox** [comment]
I'm having the same issue

**Comment by wotschofsky** [comment]
Thanks for reporting this! Can you send me a screenshot of the bot logs at startup? Feel free to blur out any identifiable information.

**Comment by resiez** [comment]
Here are my logs:
<img width="793" alt="image" src="https://github.com/wotschofsky/discord-live-translator/assets/109241213/1c8d34a9-0d79-4066-8f88-85f17d9e885c">

**Comment by eliteprox** [comment]
I have learned that you need to register slash commands with discord bot in order to use them. GitHub repo is missing documentation on how to do this. 

This is outlined in the discord bot documentation here https://discord.com/developers/docs/interactions/application-commands#slash-commands

I was able to send the folllowing request using Postman to add the `/start` slash commands to my bot. Replace CLIENTID with your bot's client id, and BOTTOKEN with your bot's token.

http post  `https://discord.com/api/v10/applications/CLIENTID/commands`
Add header `Authorization Bot BOTTOKEN`
```
{
    "name": "start",
    "type": 1,
    "description": "Start the translation",
    "options": [
        {
            "name": "target",
            "description": "Target Language",
            "type": 3,
            "required": true,
            "choices": [
                {
                    "name": "English",
                    "value": "en"
                },
                {
                    "name": "Spanish",
                    "value": "es"
                },
                {
                    "name": "French",
                    "value": "fr"
                }
            ]
        }
    ]
}
```

This is for the join command, which is required before running `/start`
```
{
    "name": "/join",
    "type": 1,
    "description": "Tell the bot to join the voice channel",
    "options": [
    ]
}
```

You can overwrite an existing slash command by posting using the same name variable. I hope this helps.

**Comment by resiez** [comment]
That fixed my issue. Thanks

**Comment by wotschofsky** [comment]
Thank your for pointing out this issue. ❤️ I've added the appropriate documentation.
